version: "3.7"
services:
  app:
    build:
      args:
        user: furquan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: imagevalidator
    container_name: imagevalidator-app
    restart: unless-stopped
    environment: 
      - COMPOSER_MEMORY_LIMIT=-1
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - imagevalidator

  db:
    image: mysql:5.7
    container_name: imagevalidator-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - imagevalidator

  nginx:
    image: nginx:alpine
    container_name: imagevalidator-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - imagevalidator

networks:
  imagevalidator:
    driver: bridge